const axios = require('axios');

const activeCampaignApi = axios.create({
  baseURL: process.env.ACTIVECAMPAIGN_URL,
  headers: {
    'Api-Token': process.env.ACTIVECAMPAIGN_API_KEY,
    'Content-Type': 'application/json'
  }
});

/**
 * Sync a contact (creates or updates)
 */
async function syncContact(email, firstName = '', lastName = '', phone = '') {
  if (!email) throw new Error('Email is required to sync contact');
  
  try {
    const response = await activeCampaignApi.post('/api/3/contact/sync', {
      contact: {
        email,
        firstName,
        lastName,
        phone
      }
    });
    return response.data.contact;
  } catch (err) {
    console.error('AC Sync Contact Error:', err?.response?.data || err.message);
    throw err;
  }
}

/**
 * Find a tag by name, or create it if it doesn't exist
 */
async function getOrCreateTag(tagName) {
  try {
    // 1. Search for tag
    const searchRes = await activeCampaignApi.get(`/api/3/tags`, {
      params: { search: tagName }
    });
    
    // exact match check
    const existingTag = searchRes.data.tags.find(
      t => t.tag.toLowerCase() === tagName.toLowerCase()
    );
    
    if (existingTag) {
      return existingTag.id;
    }
    
    // 2. Create if not found
    const createRes = await activeCampaignApi.post('/api/3/tags', {
      tag: {
        tag: tagName,
        tagType: 'contact',
        description: 'Auto-generated by Pomsky Backend'
      }
    });
    
    return createRes.data.tag.id;
  } catch (err) {
    console.error('AC Get/Create Tag Error:', err?.response?.data || err.message);
    throw err;
  }
}

/**
 * Add a tag to a contact using the tag name
 */
async function addTagByName(contactId, tagName) {
  try {
    const tagId = await getOrCreateTag(tagName);
    
    const response = await activeCampaignApi.post('/api/3/contactTags', {
      contactTag: {
        contact: contactId,
        tag: tagId
      }
    });
    return response.data.contactTag;
  } catch (err) {
    console.error('AC Add Tag Error:', err?.response?.data || err.message);
    throw err;
  }
}

/**
 * Subscribe a contact to a list
 */
async function subscribeToList(contactId, listId) {
  try {
    const response = await activeCampaignApi.post('/api/3/contactLists', {
      contactList: {
        list: listId,
        contact: contactId,
        status: 1 // 1 = Subscribed
      }
    });
    return response.data;
  } catch (err) {
    // If already subscribed, AC might throw an error - we can ignore it
    console.warn('AC Subscribe to List Warning (might already be subscribed):', err?.response?.data || err.message);
    return null;
  }
}

/**
 * Trigger an email sequence via tag
 */
async function triggerEmailByTag(email, firstName, lastName, tagName) {
  try {
    if (!process.env.ACTIVECAMPAIGN_URL || !process.env.ACTIVECAMPAIGN_API_KEY) {
       console.warn('ActiveCampaign credentials missing. Skipping email tag trigger.');
       return false;
    }

    const contact = await syncContact(email, firstName, lastName);
    if (contact && contact.id) {
      // 1. Automatically subscribe to list if LIST_ID is provided
      const listId = process.env.ACTIVECAMPAIGN_LIST_ID;
      if (listId) {
        await subscribeToList(contact.id, listId);
      } else {
        console.warn('ACTIVECAMPAIGN_LIST_ID is missing. Emails may be skipped by AC.');
      }

      // 2. Add the tag to trigger automation
      await addTagByName(contact.id, tagName);
      console.log(`Successfully added tag "${tagName}" to contact ${email}`);
      return true;
    }
    return false;
  } catch (err) {
    console.error(`Failed to trigger AC email for ${email} with tag ${tagName}`);
    return false;
  }
}

const MEMBERSHIP_TAGS = {
  breeder_free: 'POA - Breeder - free',
  breeder_silver: 'POA - Breeder - silver',
  breeder_gold: 'POA - Breeder - gold',
  shopper_monthly: 'POA - Shopper - monthly',
  shopper_lifetime: 'POA - Shopper - annually',
  shopper_annual: 'POA - Shopper - annually',
  shopper_annually: 'POA - Shopper - annually',
  owner_monthly: 'POA - Owner - monthly',
  owner_annual: 'POA - Owner - annually',
  owner_annually: 'POA - Owner - annually'
};

/**
 * Trigger ActiveCampaign tagging for a specific membership type
 */
async function triggerMembershipTag(email, fullName, membershipType) {
  const tag = MEMBERSHIP_TAGS[membershipType];
  if (!tag) {
    console.log(`No ActiveCampaign tag mapped for membership type: ${membershipType}`);
    return false;
  }

  const nameParts = (fullName || '').trim().split(/\s+/);
  const firstName = nameParts[0] || '';
  const lastName = nameParts.slice(1).join(' ') || '';

  return await triggerEmailByTag(email, firstName, lastName, tag);
}

/**
 * Trigger ActiveCampaign tagging for a user ID by fetching profile details
 */
async function triggerMembershipTagById(userId, membershipType) {
  try {
    const supabase = require('../supabase');
    const { data: profile, error } = await supabase
      .from('profiles')
      .select('email, full_name')
      .eq('id', userId)
      .single();

    if (error || !profile) {
      console.error(`Failed to fetch profile for user ${userId} to trigger membership tag:`, error?.message);
      return false;
    }

    return await triggerMembershipTag(profile.email, profile.full_name, membershipType);
  } catch (err) {
    console.error(`Error in triggerMembershipTagById for user ${userId}:`, err.message);
    return false;
  }
}

module.exports = {
  syncContact,
  getOrCreateTag,
  addTagByName,
  triggerEmailByTag,
  triggerMembershipTag,
  triggerMembershipTagById
};

