const axios = require('axios');

const activeCampaignApi = axios.create({
  baseURL: process.env.ACTIVECAMPAIGN_URL,
  headers: {
    'Api-Token': process.env.ACTIVECAMPAIGN_API_KEY,
    'Content-Type': 'application/json'
  }
});

/**
 * Sync a contact (creates or updates)
 */
async function syncContact(email, firstName = '', lastName = '', phone = '') {
  if (!email) throw new Error('Email is required to sync contact');
  
  try {
    const response = await activeCampaignApi.post('/api/3/contact/sync', {
      contact: {
        email,
        firstName,
        lastName,
        phone
      }
    });
    return response.data.contact;
  } catch (err) {
    console.error('AC Sync Contact Error:', err?.response?.data || err.message);
    throw err;
  }
}

/**
 * Find a tag by name, or create it if it doesn't exist
 */
async function getOrCreateTag(tagName) {
  try {
    // 1. Search for tag
    const searchRes = await activeCampaignApi.get(`/api/3/tags`, {
      params: { search: tagName }
    });
    
    // exact match check
    const existingTag = searchRes.data.tags.find(
      t => t.tag.toLowerCase() === tagName.toLowerCase()
    );
    
    if (existingTag) {
      return existingTag.id;
    }
    
    // 2. Create if not found
    const createRes = await activeCampaignApi.post('/api/3/tags', {
      tag: {
        tag: tagName,
        tagType: 'contact',
        description: 'Auto-generated by Pomsky Backend'
      }
    });
    
    return createRes.data.tag.id;
  } catch (err) {
    console.error('AC Get/Create Tag Error:', err?.response?.data || err.message);
    throw err;
  }
}

/**
 * Add a tag to a contact using the tag name
 */
async function addTagByName(contactId, tagName) {
  try {
    const tagId = await getOrCreateTag(tagName);
    
    const response = await activeCampaignApi.post('/api/3/contactTags', {
      contactTag: {
        contact: contactId,
        tag: tagId
      }
    });
    return response.data.contactTag;
  } catch (err) {
    console.error('AC Add Tag Error:', err?.response?.data || err.message);
    throw err;
  }
}

/**
 * Trigger an email sequence via tag
 */
async function triggerEmailByTag(email, firstName, lastName, tagName) {
  try {
    if (!process.env.ACTIVECAMPAIGN_URL || !process.env.ACTIVECAMPAIGN_API_KEY) {
       console.warn('ActiveCampaign credentials missing. Skipping email tag trigger.');
       return false;
    }

    const contact = await syncContact(email, firstName, lastName);
    if (contact && contact.id) {
      await addTagByName(contact.id, tagName);
      console.log(`Successfully added tag "${tagName}" to contact ${email}`);
      return true;
    }
    return false;
  } catch (err) {
    console.error(`Failed to trigger AC email for ${email} with tag ${tagName}`);
    return false;
  }
}

module.exports = {
  syncContact,
  getOrCreateTag,
  addTagByName,
  triggerEmailByTag
};
